server:
  port: 8761
spring:
  application:
    name: node11-seata-eureka
eureka:
  instance:
    instance-id: node11-seata-eureka
    prefer-ip-address: true
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示该端就是注册中心，维护服务实例，不去检索服务
    fetch-registry: false
    service-url:
      # 单点注册中心
      defaultZone: http://127.0.0.1:8761/eureka/